### ISSUE TITLE
Product image zoom UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Doyle-Speed-Work#1]
Bug - Product image zoom feature UI issue.
Exp - Product image zoom not working correctly on Product page.
Ref Link - https://drive.google.com/file/d/10t936l1KkxtTLSr769Qv8WS03lKEYjH_/view

**Comment by devabulabbas** [comment]
Resolved @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Bug Fixed
