### ISSUE TITLE
UI issue on product page on mozilla browser

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Doyle-Speed-Work#2]
Bug - Text UI issue on mozilla and quantity increment/decremenet button showing on mozilla but not showing on chrome and on edge.
Exp - Text UI should be same on all browser and quantity increment/decremenet button should be visible on browser UI.
Ref Link - https://drive.google.com/file/d/1EBPFvIojLBIEG4xTzJGbWZulJWYXlauP/view

**Comment by devabulabbas** [comment]
Both Live and Preview are same in mozila and both are same on chrome

**Comment by ankitcedcoss** [comment]
Bug Fixed
